## Image Manipulation

1. Transformations, affine and non affine
2. Transactaions
3. Rotations
4. Scalling, re-sizing and interpolations
5. Image Pyramids
6. Cropping
7. Airthmetic Operations
8. Bitwise Operations and Masking
9. Convolutions & Blurring
10. Sharpening
11. Thresholding and Binarization
12. Dilation, erosion, opening and closing
13. Edge Detection & Image Gradients
14. Perspective & Affine transforms
15. Mini Projects # 1-Make a Live Sketch of Yourself!

### Trasformations
    Transformations-are geometric distortions encated upon an image.
    
#### We use transformations to correct distortions or perspective issues from arising from the point of view an image was captured.

### Types:
#### * Affine
#### * Non-Affine

## Translations

#### This an affine transform that simply shifts the position of an image. 
#### We use.cv2.warpAffine to implement these transformations.

In [62]:
import cv2
import numpy as np

image=  cv2.imread(r"C:\Users\ADMIN\Downloads\landscap.jpg")

# Store height and widhth of the image

height, width = image.shape[:2]

quarter_height, quarter_widht = height/4, width/4

#       / 1 0 Tx /
#   T = /0 1 Ty /

# T is our translation matrix
T = np.float32([[1, 0, quarter_widht],[0, 1, quarter_height]])

# We use warpAffine to transform the image using the matrix, T
img_translation = cv2.warpAffine(image, T, (width, height))
cv2.imshow('Translation',img_translation)
cv2.waitKey(0)==ord("a")
cv2.destroyAllWindows() 

In [63]:
# Let's Take a look at T

print(T)

[[  1.     0.   400.  ]
 [  0.     1.   193.75]]


###############################################################################################################

### Rotations

cv2.getRoation Matrix2D(rotation_center_x,rotaition_center_y, angle of rotaion, scale)

In [64]:
import cv2
import numpy as np

image = cv2.imread(r"C:\Users\ADMIN\Downloads\autumn-poolside.jpg")
height, width = image.shape[:2]

#Divide by two to roatate the image around its centre

rotation_matrix=cv2.getRotationMatrix2D((width/2, height/2),90,1)

rotated_image = cv2.warpAffine(image, rotation_matrix,(width,height))

cv2.imshow('Roatated Image', rotated_image)
cv2.waitKey(0)==ord("a")
cv2.destroyAllWindows()

#### Notice all the black space surrounding the image.

We could now crop the image as we can calculate its new size(we havent leraned cropping yet!)

But here's another  method for simple ratations that uses the cv2.transfose function

In [65]:
# other option to Rotate

img=cv2.imread(r"C:\Users\ADMIN\Downloads\autumn-poolside.jpg")

roatated_image = cv2.transpose(img)

cv2.imshow('Roatated Image - Method 2', rotated_image)
cv2.waitKey(0)==ord("a")
cv2.destroyAllWindows()

###############################################################################################################

### Scaling, re-sizing and inerpolations

reisizing is very easy using the cv2.resize function, its arguments are:

cv2.resize(image,dsize(output image size), x scale, y scale, interpolation)

In [66]:
import cv2
import numpy as np

# Load our input image

image = cv2.imread(r"C:\Users\ADMIN\Downloads\landscap.jpg")

# Lets make our image 3/4 of its original size

image_scaled = cv2.resize(image, None, fx=0.75, fy=0.75)
cv2.imshow('Scalling - Linear Interpolation', image_scaled)
cv2.waitKey()

# Lets double the size of our image
img_scaled = cv2.resize(image, None, fx=2, fy=2, interpolation = cv2.INTER_CUBIC)
cv2.imshow('Scalli ng - Cubic Interpolation', img_scaled)
cv2.waitKey()

# Lets skew the re-sizing by setting exact dimensions
img_scaled = cv2.resize(image,(900,400), interpolation = cv2.INTER_AREA)
cv2.imshow('Scaling - Skewed Size', img_scaled)
cv2.waitKey(0)==ord("a")

cv2.destroyAllWindows()

###############################################################################################################

## Image Pyramids

Useful when scalling images in object detection.

In [67]:
import cv2

image = cv2.imread(r"C:\Users\ADMIN\Downloads\monkey-timon-the-lion-king-pumbaa-wallpaper-preview.jpg")

smaller = cv2.pyrDown(image)
larger = cv2.pyrUp(smaller)

cv2.imshow('Original',image)

cv2.imshow('Smaller', smaller)
cv2.imshow('Larger', larger)
cv2.waitKey(0)==ord('a')
cv2.destroyAllWindows()

#### for loop samaller smaller image

In [68]:
import cv2

image = cv2.imread(r"C:\Users\ADMIN\Downloads\monkey-timon-the-lion-king-pumbaa-wallpaper-preview.jpg")

cv2.imshow('Original', image)

for i in range(4):
    smaller = cv2.pyrDown(image)
    image = smaller
    cv2.imshow('Smaller ' + str(i), smaller)

    # Check for user input to break out of the loop
    key = cv2.waitKey(0)
    if key == ord('q'):
        break

cv2.destroyAllWindows()


####################################################################################################################

### Cropping

In [69]:
import cv2
import numpy as np

image = cv2.imread(r"C:\Users\ADMIN\Downloads\monkey-timon-the-lion-king-pumbaa-wallpaper-preview.jpg")
height, width = image.shape[:2]

# Lets get the starting pixel coording (top Left of cropping rectangle)
start_row, start_col = int(height * .25), int(width * .25)

# let's get the ending pixel coordinates (bottom right)
end_row, end_col = int(height * .75), int(width * .75)

# Simply use indexing to crop out the rectangle we desire
cropped = image[start_row:end_row, start_col:end_col]

cv2.imshow("Original Image", image)
cv2.waitKey(0)
cv2.imshow("Cropped Image",cropped)
cv2.waitKey(0)==ord('a')
cv2.destroyAllWindows()

####################################################################################################################

### Arithmatic Operations

These are simple operations that allow us to directly add to the color intensity.

Calculates the per-element operation of two arrays. The overall effect is increasing or decresing brightness.

In [70]:
import cv2
import numpy as np

image = cv2.imread(r"C:\Users\ADMIN\Downloads\monkey-timon-the-lion-king-pumbaa-wallpaper-preview.jpg")

# Create a matrix of ones, then multiply it by a scaler of 100
# This gives a matrix with same dimensions of our image with all values being 100
M = np.ones(image.shape, dtype = "uint8") * 75    #<-- you can change IMGE brightness changing value

# We use this to add this matrix M, to our image
# Notice the increase in brightness

added = cv2.add(image, M)
cv2.imshow("Added", added)

# Linkwise we can also sunstract
# Notice the decrease in the brightness

substracted = cv2.subtract(image, M)
cv2.imshow("Subtracted", substracted)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
M = np.ones(image.shape, dtype = "uint8") * 75
print(M)

[[[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 ...

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]]


##################################################################################################################

### Bitwise Operation and Masking

#### To demonstrate these operations lets create some simple images

In [71]:
import cv2
import numpy as np

# If you're wondering why only two dimensions, well this is a grayscale image,
# if we were doing a colored image, we'd use
# rectangle = np.zeros((300,300, 3), np.uint8)

# Making a square
square = np.zeros((300,300), np.uint8)
cv2.rectangle(square,(50,50),(250,250),255,-2)
cv2.imshow("Square", square)
cv2.waitKey(0)

# Making an ellipse
ellipse = np.zeros((300,300), np.uint8)
cv2.ellipse(ellipse,(150,150),(150,150),30,0,180,255,-1)
cv2.imshow("Ellipse", ellipse)
cv2.waitKey(0)

cv2.destroyAllWindows()


##  Experimenting with some bitwise operations

In [72]:
import cv2
import numpy as np

# Shows only where they intersect
And = cv2.bitwise_and(square,ellipse)
cv2.imshow("AND", And)
cv2.waitKey(0)

# Show where either square or ellipse is
bitwiseOr = cv2.bitwise_or(square,ellipse)
cv2.imshow("OR", bitwiseOr)
cv2.waitKey(0)

# Show where either exists by itself
bitwiseXor = cv2.bitwise_xor(square,ellipse)
cv2.imshow("XOR", bitwiseXor)
cv2.waitKey(0)

# Show everything that isn't part of the square
bitwiseNot_sq = cv2.bitwise_not(square)
cv2.imshow("NOT - square", bitwiseNot_sq)
cv2.waitKey(0)

cv2.destroyAllWindows()


#################################################################################################################

## Convolutions and Blurring

In [73]:
import cv2
import numpy as np

image = cv2.imread(r"C:\Users\ADMIN\Downloads\ch.jpg")
cv2.imshow("Original Image", image)
cv2.waitKey(0)

# Creating our 3 x 3 kernel
kernel_3x3 = np.ones((3,3),np.float32)/9

# We use the cv2.fitler2D to convolve the kernel with an image
blurred = cv2.filter2D(image, -1, kernel_3x3)
cv2.imshow('3x3 Kernel Blurring',blurred)
cv2.waitKey(0)

# Creating our 7 x 7 kernel
kernel_7x7 = np.ones((7,7), np.float32) / 49

blurred2 = cv2.filter2D(image, -1, kernel_7x7)
cv2.imshow('7x7 Kernel Blurring', blurred2)
cv2.waitKey(0)

cv2.destroyAllWindows()

 ## Other commonly used blurring methods in OpenCV

In [74]:
import cv2
import numpy as np

image = cv2.imread(r"C:\Users\ADMIN\Downloads\birds.jpg")

# Averagingdone by convolving the image with a normalized box filter.
# This takes the pixels under the box and replaces the central element
# Box size needs to odd and positive

blur = cv2.blur(image,(3,3))
cv2.imshow('Averaging', blur)
cv2.waitKey(0)

# Instead of box filter, gaussian kernel
Gaussian = cv2.blur(image,(7,7),0)
cv2.imshow('Gaussian Blurring', Gaussian)
cv2.waitKey(0)

# Takes median of all the pixels under kernel area and central
# element is replaced with this meadian value
median = cv2.medianBlur(image, 5)
cv2.imshow('Meadian Blurring',median)
cv2.waitKey(0)

# Bilateral is very effective in noise removal while keeping edges sharp
bilateral = cv2.bilateralFilter(image, 9, 75, 75)
cv2.imshow('Bilateral Bluring',bilateral)
cv2.waitKey(0)
cv2.destroyAllWindows()

##################################################################################################################

## Image De-noising -Non-Local Means Denoising

In [75]:
import cv2
import numpy as np

image = cv2.imread(r"C:\Users\ADMIN\Downloads\ch.jpg")

# Parameters, after Non are - the filter strenght 'h' (5-10 is a good range)
# Next is hForColorComponents, set as same value as h again

dst = cv2.fastNlMeansDenoisingColored(image, None, 6, 6, 7, 21)

cv2.imshow('Fast Means Denoising', dst)
cv2.waitKey(0)

cv2.destroyAllWindows()

### There are 4 variations of Non-Local Means Denosing:


* cv2.fastNMeansDenoising()-works with a single grayscale images
* cv2.fastNMeansDenoisingColored()-works with color image.
* cv2.fastNMeansDenoisingMulti() - works with image sequence captured in short period of time(grayscale images)
* cv2.fastNMeansDenoisingColoredMulti() -same as above, but for color images

#################################################################################################################

## Sharpening

By altering our we can implement sharpning, which has the effects of in strenghening or emphasizing edges in an image.

In [76]:
import cv2
import numpy as np

image = cv2.imread(r"C:\Users\ADMIN\Downloads\ch.jpg")
cv2.imshow('Original', image)

# Crate our shapening kernel, we dont normalize since the
# the values in the matrix sum to 1

kernel_sharpening = np.array([[-1,-1,-1],
                             [-1,9,-1],
                             [-1,-1,-1]])

# applying different kernels to the input image
sharpened = cv2.filter2D(image, -1, kernel_sharpening)

cv2.imshow('Image Sharpening', sharpened)

cv2.waitKey(0)
cv2.destroyAllWindows()